services:
  db:
    image: postgres:15
    container_name: marketplace_db
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-marketplace}
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-nthusi2017} 
    restart: always
    volumes:
      - marketplace_db:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  
  backend:
    container_name: martketplace_backend
    build: ./backend/
    ports:
      - "${APP_PORT:-8888}:8888"
    environment:
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    restart: always
  frontend:
    container_name: marketplace_frontend
    build: ./frontend/
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    restart: always    
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "${MINIO_APP_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data    
volumes:
 marketplace_db:
   external: false
 minio_data:
   external: false 