services:
  db:
    image: postgres:15
    container_name: marketpace_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-marketplace}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nthusi2017} 
    restart: always
    volumes:
      - marketpace_db:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  
  backend:
    container_name: martketplace_backend
    build: ./backend/
    ports:
      - "8888:8888"
    environment:
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
    restart: always
  frontend:
    container_name: marketplace_frontend
    build: ./frontend/
    ports:
      - "3000:3000"
    restart: always    
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "${MINIO_APP_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data    
volumes:
 marketpace_db:
   external: false
 minio_data:
   external: false 